import os
import re

content_map = {
    # UNIT 1
    "1.1.1": "* **Definition:** A computer is an electronic device that processes data into meaningful information.\n* **Key Components:** Hardware (physical parts) and Software (programs).\n* **Lab Safety:**\n  1. No food or beverages near the workstations.\n  2. Ensure all cables are securely plugged in.\n  3. Always log off or shut down properly before leaving.\n  4. Do not attempt to repair hardware issues yourself; notify the IT admin.",
    "1.1.2": "* **CPU (Central Processing Unit):** The 'brain' of the computer.\n  * **ALU (Arithmetic Logic Unit):** Performs math and logical operations.\n  * **CU (Control Unit):** Directs the flow of data.\n* **Memory (RAM vs ROM):**\n  * **RAM (Random Access Memory):** Temporary, volatile storage for active tasks. Cleared on shutdown.\n  * **ROM (Read-Only Memory):** Non-volatile, holds boot instructions.",
    "1.1.3": "* **Purpose:** Input devices allow users to send data and control signals to the computer.\n* **Keyboard:** Used for text entry and command shortcuts (e.g., Ctrl+C, Ctrl+V).\n* **Mouse/Touchpad:** Pointing devices for GUI navigation (click, double-click, drag-and-drop).\n* **Scanners:** Converts physical documents into digital formats (PDF, JPEG) used in aviation admin.",
    "1.1.4": "* **Purpose:** Output devices translate processed digital data into human-readable form.\n* **Monitors:** Visual display. Measured in resolution (e.g., 1080p, 4K) and refresh rate.\n* **Printers:** \n  * *Laser Printers:* Fast, uses toner, best for high-volume text.\n  * *Inkjet Printers:* Uses liquid ink, best for photos/color.\n  * *Thermal Printers:* Used for boarding passes and luggage tags.",
    "1.1.5": "* **Purpose:** Long-term, non-volatile data retention.\n* **HDD (Hard Disk Drive):** Uses magnetic spinning platters. Cheaper, higher capacity, but slower and fragile.\n* **SSD (Solid State Drive):** Uses flash memory. No moving parts, much faster boot/load times, more durable.\n* **USB Flash Drives:** Portable flash memory for transferring files between disconnected devices.",
    "1.1.6": "* **Step 1:** Observe the external ports (USB, HDMI, Ethernet).\n* **Step 2:** Identify the power supply unit and cooling fans.\n* **Step 3:** Locate the motherboard, CPU cooler, and RAM slots.\n* **Step 4:** Note how storage drives (SATA/NVMe) are connected.\n* **Safety Warning:** Always ground yourself before touching internal components to prevent static discharge.",
    "1.2.1": "* **Hardware:** The physical, tangible components you can touch (Monitor, Keyboard, RAM, Motherboard).\n* **Software:** The intangible set of instructions that tells the hardware what to do (Windows, MS Word, Chrome).\n* **The Relationship:** Hardware is useless without software to drive it; software cannot execute without hardware.",
    "1.2.2": "* **System Software:** Programs designed to run the computer's hardware and application programs.\n  * *Examples:* Windows, macOS, Linux, Device Drivers.\n* **Application Software:** Programs designed to help the user perform specific tasks.\n  * *Examples:* Microsoft Office, Web Browsers, Aviation ERP systems.",
    "1.2.3": "* **Word Processors:** Microsoft Word (Drafting memos, incident reports).\n* **Spreadsheets:** Microsoft Excel (Crew scheduling, budgeting, passenger manifest tracking).\n* **Presentation:** Microsoft PowerPoint (Safety briefings, management meetings).\n* **Industry-Specific:** Amadeus/Sabre (GDS for ticketing), Flight Dispatch software.",
    "1.2.4": "* **Commercial/Proprietary License:** Software you must purchase. Source code is closed. (e.g., MS Office).\n* **Open-Source Software (OSS):** Free to use and modify. Source code is public. (e.g., Linux, Mozilla Firefox).\n* **Freeware:** Free to use, but source code is closed. (e.g., Adobe Acrobat Reader).\n* **Subscription (SaaS):** Pay a monthly/annual fee for access (e.g., Microsoft 365).",
    "1.2.5": "* **Installing Windows Apps:**\n  1. Download the installer (.exe or .msi).\n  2. Double-click the file and follow the Setup Wizard.\n  3. Accept the End User License Agreement (EULA) and choose the install directory.\n* **Uninstalling:**\n  1. Open the Start Menu and search for 'Add or remove programs'.\n  2. Locate the app in the list.\n  3. Click 'Uninstall' and follow prompts to cleanly remove files.",
    "1.2.6": "* **Step 1:** Open the Windows Start Menu.\n* **Step 2:** Browse the 'All Apps' list to identify pre-installed system tools (e.g., Calculator, Notepad).\n* **Step 3:** Locate productivity applications (Word, Excel).\n* **Step 4:** Check the system tray (bottom right) for background software (Antivirus, Cloud Sync).",
    "1.3.1": "* **Definition:** An OS acts as an intermediary between the user and the computer hardware.\n* **Functions:** Memory management, process management, file management, and hardware abstraction.\n* **Windows OS:** The dominant OS in enterprise environments, known for its Graphical User Interface (GUI).",
    "1.3.2": "* **Desktop:** The main workspace where shortcuts and files are kept.\n* **Taskbar:** The bar at the bottom showing running apps and pinned shortcuts.\n* **Start Menu:** The central hub for launching applications, accessing settings, and shutting down.\n* **System Tray:** Located on the far right of the taskbar; shows network, battery, volume, and clock.",
    "1.3.3": "* **Minimize:** Hides the window to the taskbar without closing it (Shortcut: Win + Down Arrow).\n* **Maximize:** Expands the window to fill the entire screen (Shortcut: Win + Up Arrow).\n* **Restore/Resize:** Drag the edges or corners of a window to manually adjust its size.\n* **Snap Assist:** Drag a window to the left/right edge of the screen to snap it to exactly half the monitor. Great for multitasking.",
    "1.3.4": "* **Accessing Settings:** Press `Win + I` or click the gear icon in the Start Menu.\n* **Display Settings:** Right-click the desktop -> Display settings. Here you can change screen resolution and scale (text size).\n* **Personalization:** Right-click the desktop -> Personalize. Change background wallpaper, themes, and lock screen.\n* **Sound & Network:** Managed via the Settings app to connect to Wi-Fi or change output devices.",
    "1.3.5": "* **Administrator Accounts:** Full control over the system. Can install software and change system-wide settings.\n* **Standard User:** Can use apps and save files, but cannot make system-level changes. Best for daily security.\n* **UAC (User Account Control):** The prompt that asks 'Do you want to allow this app to make changes?'. It prevents unauthorized background installations.",
    "1.3.6": "* **Step 1:** Right-click the Desktop and select 'Personalize'.\n* **Step 2:** Change the background image to a solid color.\n* **Step 3:** Go to 'Themes' and switch between Light and Dark mode.\n* **Step 4:** Right-click the Taskbar, select 'Taskbar settings', and toggle 'Automatically hide the taskbar'.",
    "1.4.1": "* **Drives:** The root storage locations (e.g., C: for OS, D: for Data).\n* **Directories/Folders:** Containers used to organize files logically.\n* **Subfolders:** Folders nested inside other folders (e.g., `C:\\Aviation\\Manifests\\2026`).\n* **File Paths:** The exact address of a file on the computer (e.g., `C:\\Users\\Admin\\Documents\\report.docx`).",
    "1.4.2": "* **Creating a Folder:** Right-click empty space -> New -> Folder. Type a name and press Enter.\n* **Renaming:** Right-click the file/folder -> Rename (or click it and press `F2`). Use clear, descriptive names.\n* **Deleting:** Right-click -> Delete (or press `Del`). \n* **Recycle Bin:** Deleted files go here first. You can restore them unless you empty the bin (or use `Shift + Del` to permanently delete).",
    "1.4.3": "* **Copy (Ctrl + C):** Duplicates the file. The original stays in place.\n* **Cut (Ctrl + X):** Prepares the file to be moved. The original will be removed once pasted.\n* **Paste (Ctrl + V):** Places the copied or cut file into the new destination folder.\n* **Drag and Drop:** Clicking and dragging a file to a new folder. (Holding Ctrl while dragging forces a copy).",
    "1.4.4": "* **Definition:** The 3 or 4 letters after the dot in a filename, indicating the file format.\n* **Common Extensions:**\n  * Document: `.docx`, `.pdf`, `.txt`\n  * Image: `.jpg`, `.png`\n  * Spreadsheet: `.xlsx`, `.csv`\n* **Default Apps:** Windows uses the extension to know which app to open. (e.g., `.docx` opens MS Word). You can change this via 'Open with...'.",
    "1.4.5": "* **Windows Search:** Use the search bar in the Taskbar or top right of File Explorer.\n* **Filters:** You can narrow down searches by type, date modified, or size.\n  * *Example:* Search `kind:pdf` to only find PDF documents.\n  * *Example:* Search `datemodified:today` to find recent work.\n* **Wildcards:** Use `*` to represent any text. E.g., `*.xlsx` finds all Excel files.",
    "1.4.6": "* **Step 1:** Open the provided 'Downloads_Mess' folder.\n* **Step 2:** Create three new folders: 'Images', 'Documents', and 'Spreadsheets'.\n* **Step 3:** Sort the messy files by 'Type'.\n* **Step 4:** Select all `.jpg` and `.png` files and move (Cut/Paste) them into 'Images'. Repeat for documents and spreadsheets.",
    "1.5.1": "* **Opening Task Manager:** Press `Ctrl + Shift + Esc`.\n* **Processes Tab:** Shows all running apps and background processes. Useful for identifying what is slowing down the PC.\n* **Performance Tab:** Shows real-time usage graphs for CPU, Memory, Disk, and Network.\n* **Force Quitting:** If an app is 'Not Responding', right-click it in the Processes tab and select 'End Task'.",
    "1.5.2": "* **USB Devices (Plug & Play):** Most modern mice, keyboards, and flash drives can be plugged in and used immediately.\n* **Safe Removal:** For storage devices (USB drives, external HDDs), you must safely eject them to prevent data corruption.\n  * *Steps:* Click the USB icon in the System Tray -> 'Eject [Device Name]' -> Wait for the 'Safe to Remove' notification.",
    "1.5.3": "* **Disk Cleanup:** Removes temporary files, system cache, and empties the recycle bin to free up space.\n* **Windows Defender / Security:** Built-in antivirus. Run a 'Quick Scan' if the system is acting suspiciously.\n* **Windows Update:** Regularly checking for updates ensures security patches and bug fixes are applied.",
    "1.5.4": "* **The 3-2-1 Rule:** Keep 3 copies of your data, on 2 different media types, with 1 copy off-site (cloud).\n* **Local Backups:** Copying critical files to an external Hard Drive or USB.\n* **Cloud Backups:** Using OneDrive or Google Drive to automatically sync your 'Documents' folder to the cloud. Protects against hardware failure.",
    "1.5.5": "* **Review Topics:** \n  * Hardware vs Software distinction.\n  * Identifying Input/Output/Storage devices.\n  * Navigating the Windows OS (Taskbar, Windows management).\n  * File management (Copy, Paste, Folders, Extensions).\n  * Basic troubleshooting (Task Manager, Safe Eject).\n* **Q&A:** Open floor for student questions.",
    "1.5.6": "* **Task 1:** Create a folder hierarchy: `Aviation > Sem1 > Computing`.\n* **Task 2:** Open a text editor, write a sentence, and save it as `test.txt` in the Computing folder.\n* **Task 3:** Open Task Manager, identify the text editor process, and 'End Task'.\n* **Task 4:** Rename `test.txt` to `assessment.txt` and move it to the Desktop.",

    # UNIT 2
    "2.1.1": "* **The Ribbon:** The tabbed toolbar at the top (Home, Insert, Layout, etc.).\n* **Quick Access Toolbar:** The top-left corner (Save, Undo, Redo).\n* **The Document Area:** The digital 'paper' where you type.\n* **Status Bar:** Bottom edge showing page count, word count, and zoom controls.",
    "2.1.2": "* **Creating:** Open Word -> Click 'Blank Document' (or use `Ctrl + N`).\n* **Saving for the first time (Save As):** File -> Save As -> Choose location -> Name the file. (Shortcut: `F12`).\n* **Saving updates (Save):** File -> Save (Shortcut: `Ctrl + S`). Do this frequently!\n* **Opening:** File -> Open -> Browse to locate an existing `.docx` file (Shortcut: `Ctrl + O`).",
    "2.1.3": "* **Selecting Text:**\n  * Double-click: Selects a word.\n  * Triple-click: Selects an entire paragraph.\n  * `Ctrl + A`: Selects the entire document.\n* **Cursor Movement:**\n  * `Home` / `End`: Jump to beginning/end of the line.\n  * `Ctrl + Left/Right Arrow`: Jump word by word.",
    "2.1.4": "* **Location:** Home Tab -> Font Group.\n* **Font Face & Size:** Choose professional fonts (Arial, Calibri, Times New Roman) and readable sizes (11-12pt for body).\n* **Emphasis Shortcuts:**\n  * **Bold:** `Ctrl + B` (Use for headers or key terms)\n  * *Italic:* `Ctrl + I` (Use for book titles or foreign words)\n  * <u>Underline:</u> `Ctrl + U`\n* **Font Color:** Use the 'A' icon with the colored underline. Stick to black/dark gray for professional docs.",
    "2.1.5": "* **Format Painter:** Copies all formatting from one piece of text and applies it to another.\n  * *How to use:* Select formatted text -> Click 'Format Painter' (paintbrush icon) -> Highlight the target text.\n  * *Tip:* Double-click the Format Painter to apply the format to multiple different areas.\n* **Clear Formatting:** The 'A' with an eraser icon. Removes all bold, colors, and font changes, returning text to the default plain style.",
    "2.1.6": "* **Step 1:** Open a blank document.\n* **Step 2:** Type a standard memo header: TO:, FROM:, DATE:, SUBJECT:.\n* **Step 3:** Use Bold on the header labels.\n* **Step 4:** Write a 3-sentence body about a 'New Boarding Procedure'.\n* **Step 5:** Save As `Boarding_Memo_YourName.docx`.",
    "2.2.1": "* **Location:** Home Tab -> Paragraph Group.\n* **Left Align (`Ctrl + L`):** Default standard for English text.\n* **Center Align (`Ctrl + E`):** Used for titles and headings.\n* **Right Align (`Ctrl + R`):** Often used for dates in formal letters.\n* **Justify (`Ctrl + J`):** Aligns text to both left and right margins, creating clean edges (common in newspapers and textbooks).",
    "2.2.2": "* **Line Spacing:** The vertical space between lines of text within the same paragraph.\n  * *Standard:* 1.15 or 1.5 for readability. 2.0 (Double) for academic drafts.\n* **Paragraph Spacing:** The space Before and After a paragraph.\n  * *Best Practice:* Add space *after* paragraphs instead of pressing 'Enter' twice. Adjust via Layout Tab -> Spacing.",
    "2.2.3": "* **Bulleted Lists:** Used for unordered items (e.g., a packing list, features).\n  * *Creation:* Type `*` and press Space, or click the Bullet icon in the Home tab.\n* **Numbered Lists:** Used for sequential steps or ranked items (e.g., emergency procedures).\n  * *Creation:* Type `1.` and press Space, or click the Numbering icon.\n* **Adjusting:** Use 'Increase/Decrease Indent' buttons to move list items left or right.",
    "2.2.4": "* **Definition:** Lists that contain sub-lists (e.g., 1, 1.1, 1.1.1 or I, A, 1, a).\n* **How to Create:**\n  1. Start a standard numbered list.\n  2. Press `Enter` to go to the next line.\n  3. Press `Tab` to indent and create a sub-level.\n  4. Press `Shift + Tab` to promote the item back to the higher level.\n* **Usage:** Essential for technical manuals, legal contracts, and structured reports.",
    "2.2.5": "* **First Line Indent:** Indents only the first line of a paragraph. (Common in books). Usually created by pressing `Tab` once.\n* **Hanging Indent:** The first line is flush left, but subsequent lines are indented. (Used in Bibliographies/References).\n* **Tab Stops:** Define exactly where the cursor jumps when you press `Tab`. Set them by clicking on the horizontal ruler at the top of the page.",
    "2.2.6": "* **Step 1:** Open the provided raw text file containing the 'Uniform Policy'.\n* **Step 2:** Center and Bold the main title. Change font size to 16pt.\n* **Step 3:** Justify all body paragraphs and set Line Spacing to 1.15.\n* **Step 4:** Convert the list of approved uniform items into a Bulleted List.\n* **Step 5:** Convert the disciplinary procedure steps into a Numbered List.",
    "2.3.1": "* **Inserting a Table:** Insert Tab -> Table. Drag your mouse over the grid to choose columns x rows (e.g., 3x4).\n* **Drawing a Table:** Insert -> Table -> Draw Table. Gives you a pencil tool to draw custom rows/columns manually (useful for complex forms).\n* **Navigation:** Use `Tab` to move to the next cell. Pressing `Tab` in the very last cell automatically creates a new row.",
    "2.3.2": "* **Adding:** \n  * Right-click inside a cell -> Insert -> Choose Insert Rows Above/Below or Columns Left/Right.\n  * Or, click the '+' sign that appears when you hover over the border between rows/columns.\n* **Deleting:**\n  * Select the rows/columns -> Right-click -> Delete Rows/Columns. (Pressing `Backspace` deletes the row; pressing `Delete` only clears the text inside).",
    "2.3.3": "* **Merging Cells:** Combines two or more adjacent cells into one large cell. \n  * *Usage:* Creating a single title header across multiple columns.\n  * *Steps:* Highlight cells -> Right-click -> Merge Cells.\n* **Splitting Cells:** Divides a single cell into multiple new columns or rows.\n  * *Steps:* Right-click cell -> Split Cells -> Choose number of columns/rows.",
    "2.3.4": "* **Table Design Tab:** Appears only when you click inside a table.\n* **Table Styles:** Pre-formatted color schemes. Select the table -> Table Design -> Click the drop-down gallery to pick a professional style.\n* **Shading:** Manually fill a specific cell with color (e.g., highlighting a total row).\n* **Borders:** Add, remove, or thicken the lines around cells. Useful for creating invisible tables for layout purposes.",
    "2.3.5": "* **Images:** Insert -> Pictures. You can insert from your device or online.\n  * *Wrap Text:* Crucial step! Click the image -> Wrap Text (e.g., 'Square' or 'Tight') to allow text to flow around the image.\n* **Shapes:** Insert -> Shapes. Great for drawing arrows or callout boxes.\n* **SmartArt:** Insert -> SmartArt. Instantly creates professional graphics like organizational charts, process flows, and cycle diagrams.",
    "2.3.6": "* **Step 1:** Create a 4x5 table. \n* **Step 2:** Label headers: Flight No, Destination, Departure Time, Gate.\n* **Step 3:** Apply a professional Blue 'Table Style' with a dark header row.\n* **Step 4:** Merge the top row to add a master title: \"Morning Departures\".\n* **Step 5:** Insert a small airplane icon (Insert -> Icons) next to the master title.",
    "2.4.1": "* **Location:** Layout Tab.\n* **Margins:** The blank space around the edges of the page. Standard is 1 inch. Use 'Narrow' to fit more data, or 'Custom' for letterheads.\n* **Orientation:** \n  * *Portrait:* Vertical (Standard for documents).\n  * *Landscape:* Horizontal (Better for wide tables or certificates).\n* **Size:** Standard is A4 (international) or Letter (US). Must match your physical printer paper.",
    "2.4.2": "* **Headers & Footers:** Text that repeats at the top (Header) or bottom (Footer) of every page. \n  * *Usage:* Company logos, document titles, confidentiality notices.\n  * *Access:* Double-click the very top or bottom blank edge of the page.\n* **Page Numbers:** Insert Tab -> Page Number. Can be placed top, bottom, or in the margins. You can set them to not appear on the title page.",
    "2.4.3": "* **Page Break (`Ctrl + Enter`):** Forces text immediately to the start of the next page. *Never* use repeated 'Enters' to get to a new page!\n* **Section Break:** Layout Tab -> Breaks -> Section Break (Next Page). \n  * *Why?* Section breaks allow you to change formatting for just one part of the document (e.g., making page 2 Landscape while page 1 stays Portrait).",
    "2.4.4": "* **Spelling (Red squiggly line):** Indicates a misspelled word.\n* **Grammar (Blue/Double-blue line):** Indicates grammatical errors or phrasing issues.\n* **Review Tab -> Spelling & Grammar:** Runs a full check on the document.\n* **Thesaurus:** Select a word -> Shift + F7. Provides synonyms to elevate your professional vocabulary.",
    "2.4.5": "* **Print Preview:** File -> Print (Shortcut: `Ctrl + P`). Shows exactly how the document will look on paper.\n* **Print Settings:** Choose which printer, print range (e.g., Pages 1-3), single/double-sided, and collation.\n* **Export to PDF:** File -> Save As -> Change file type to `.pdf`. \n  * *Why PDF?* Locks the formatting so it looks identical on any device and cannot be easily edited.",
    "2.4.6": "* **Step 1:** Open the drafted Incident Report.\n* **Step 2:** Insert a Page Break before the 'Appendices' section.\n* **Step 3:** Add a Header with the text 'CONFIDENTIAL - Internal Use Only'.\n* **Step 4:** Add Page Numbers to the bottom right of the Footer.\n* **Step 5:** Run a Spelling & Grammar check, then Export as a PDF.",
    "2.5.1": "* **What are Styles?** Pre-configured combinations of font, size, color, and paragraph spacing (Home Tab -> Styles gallery).\n* **Heading 1, Heading 2:** Used to structure your document hierarchically.\n* **Benefits:**\n  1. Consistency: All headings look exactly the same.\n  2. Efficiency: Change the 'Heading 1' style once, and it updates everywhere.\n  3. Navigation: Allows use of the Navigation Pane to jump between sections.",
    "2.5.2": "* **Prerequisite:** You *must* format your document titles using Styles (Heading 1, Heading 2) for this to work.\n* **Steps:**\n  1. Place cursor where you want the TOC (usually a blank page after the title).\n  2. Go to References Tab -> Table of Contents.\n  3. Choose an Automatic Table.\n* **Updating:** If you add text and page numbers change, simply click the TOC and select 'Update Table'.",
    "2.5.3": "* **Cover Pages:** Insert Tab -> Cover Page. Provides professional, pre-designed title pages (Title, Author, Date). It automatically suppresses headers/page numbers on this first page.\n* **Watermarks:** Design Tab -> Watermark. Faded text or images placed behind the main document text.\n  * *Common uses:* 'DRAFT', 'CONFIDENTIAL', or a faint company logo.",
    "2.5.4": "* **Definition:** A tool to create personalized letters/emails for many recipients using a single template and a data source (like an Excel list).\n* **The Process:**\n  1. Mailings Tab -> Start Mail Merge -> Letters.\n  2. Select Recipients (Browse for your Excel file of names/addresses).\n  3. Insert Merge Fields (e.g., `<<First_Name>>`) into your letter.\n  4. Finish & Merge -> Print Documents.",
    "2.5.5": "* **Review Topics:**\n  * Formatting text and paragraphs.\n  * Creating and styling Tables.\n  * Inserting Visuals (Images, SmartArt) and Wrapping Text.\n  * Document Layout (Margins, Headers, Page Breaks).\n  * Advanced automation (Styles, TOC, PDFs).\n* **Q&A:** Clarify any doubts before the assessment.",
    "2.5.6": "* **Task:** You will receive a raw, unformatted text file detailing an Aviation Market Analysis.\n* **Requirements:**\n  1. Apply Heading 1 and Heading 2 styles appropriately.\n  2. Insert an Automatic Table of Contents.\n  3. Convert the provided data into a formatted Table.\n  4. Add a Cover Page and 'DRAFT' Watermark.\n  5. Save as a PDF.",

    # UNIT 3
    "3.1.1": "* **Excel Interface:** The Ribbon, Name Box, Formula Bar, and grid.\n* **Workbook vs Worksheet:**\n  * *Workbook:* The entire Excel file (`.xlsx`).\n  * *Worksheet (Sheet):* A single page or tab within the workbook.\n* **Navigation:** Click the `+` at the bottom to add new sheets. Right-click a sheet tab to rename or color-code it.",
    "3.1.2": "* **Columns:** Vertical pillars identified by Letters (A, B, C...). Excel has up to 16,384 columns.\n* **Rows:** Horizontal lines identified by Numbers (1, 2, 3...). Excel has over 1 million rows.\n* **Cells:** The intersection of a row and column, identified by its address (e.g., `B4`).\n* **Navigation Shortcuts:** \n  * `Ctrl + Arrow Keys`: Jump to the edge of a data block.\n  * `Ctrl + Home`: Jump to cell A1.",
    "3.1.3": "* **Text (Labels):** Automatically aligns to the Left. Used for names, categories.\n* **Numbers (Values):** Automatically aligns to the Right. Used for calculations.\n* **Dates:** Excel treats dates as serial numbers. (e.g., Type `1/15/26` or `15-Jan`).\n* **Editing Cells:** Double-click a cell or press `F2` to edit its contents without deleting the existing data.",
    "3.1.4": "* **AutoFill (Fill Handle):** The small green square in the bottom-right corner of an active cell. Click and drag it to copy data or continue a series (e.g., Jan, Feb, Mar... or 1, 2, 3...).\n* **Flash Fill (`Ctrl + E`):** Automatically extracts or combines data based on a pattern you provide.\n  * *Example:* If Column A is 'John' and Column B is 'Doe', type 'John Doe' in Column C, press `Ctrl + E`, and Excel fills the rest.",
    "3.1.5": "* **Selecting a Range:** Click and drag from the top-left cell to the bottom-right cell. Address is written as `A1:C5`.\n* **Selecting Entire Columns/Rows:** Click the Column Letter (A) or Row Number (1) header.\n* **Selecting Non-Adjacent Cells:** Hold down the `Ctrl` key while clicking different cells or dragging different ranges.",
    "3.1.6": "* **Step 1:** Open a blank Workbook.\n* **Step 2:** In row 1, type headers: Passenger Name, PNR, Flight No, Seat, Date.\n* **Step 3:** Enter 5 rows of dummy data.\n* **Step 4:** Use AutoFill to drag a sequential date down the Date column.\n* **Step 5:** Save the file as `Passenger_List.xlsx`.",
    "3.2.1": "* **General vs Specific Formats:** Home Tab -> Number Group.\n* **Currency / Accounting:** Adds a currency symbol ($, €, ₹) and two decimal places. (Accounting aligns symbols neatly on the left).\n* **Percentages:** Converts a decimal to a percentage (e.g., 0.85 becomes 85%).\n* **Dates:** Short Date (1/15/2026) vs Long Date (Thursday, January 15, 2026).",
    "3.2.2": "* **Font Formatting:** Standard Bold, Italic, Color options (Home Tab).\n* **Borders:** By default, Excel gridlines do not print. You must add Borders (Home Tab -> Borders icon) to create visible grid tables.\n  * *Common use:* Thick Outside Borders for headers, All Borders for data grids.",
    "3.2.3": "* **Alignment:** Align text vertically (Top, Middle, Bottom) and horizontally (Left, Center, Right).\n* **Wrap Text:** Forces long text to break into multiple lines within the same cell, expanding the row height instead of bleeding into the next column.\n* **Merge & Center:** Combines multiple selected cells into one large cell and centers the text. *Warning: Avoid merging data cells, only use for Titles.*",
    "3.2.4": "* **Manual Adjustment:** Hover between column letters (e.g., between A and B). Click and drag the double-arrow to resize.\n* **AutoFit:** Double-click the boundary between column letters. Excel automatically resizes the column to perfectly fit the longest text inside it.\n* **Uniform Sizing:** Select multiple columns, then resize one; all selected columns will snap to that exact width.",
    "3.2.5": "* **Inserting:** Right-click a row number -> Insert (adds a new row *above*). Right-click a column letter -> Insert (adds a column to the *left*).\n* **Deleting:** Right-click the header -> Delete.\n* **Hiding:** Right-click -> Hide. Useful to temporarily remove columns from view without deleting the data. (Right-click surrounding headers -> Unhide to restore).",
    "3.2.6": "* **Step 1:** Open the raw `Sales_Report`.\n* **Step 2:** Merge & Center the main title across columns A-E. Make it Bold and 16pt.\n* **Step 3:** Select the 'Revenue' column and format it as Currency.\n* **Step 4:** Select the header row, Apply Wrap Text, Bold, and a light blue background color.\n* **Step 5:** AutoFit all columns and add 'All Borders'.",
    "3.3.1": "* **The Golden Rule:** Every single formula and function in Excel MUST start with an Equals Sign (`=`).\n* **Formula Bar:** The white bar above the grid where the active formula is displayed.\n* **Syntax Example:** `=A1+B1` tells Excel to add the value inside cell A1 to the value inside B1.\n* **Constants vs References:** `=5+10` is static. `=A1+B1` is dynamic and updates automatically if A1 changes.",
    "3.3.2": "* **Addition (`+`):** Example: `=C2+D2` (Adds base fare + taxes).\n* **Subtraction (`-`):** Example: `=E2-F2` (Calculates gross weight minus fuel).\n* **Usage:** Click the cell where you want the answer -> Type `=` -> Click the first cell -> Type the operator -> Click the second cell -> Press `Enter`.",
    "3.3.3": "* **Multiplication (`*`):** Uses the asterisk. Example: `=B2*C2` (Calculates Ticket Price * Number of Tickets).\n* **Division (`/`):** Uses the forward slash. Example: `=TotalCost/12` (Calculates monthly cost).\n* **Error Prevention:** Dividing by an empty cell or zero will result in a `#DIV/0!` error.",
    "3.3.4": "* **PEMDAS Rule:** Excel calculates in this strict order: Parentheses, Exponents, Multiplication/Division, Addition/Subtraction.\n* **Example without parentheses:** `=5+2*3` results in 11 (2*3 happens first).\n* **Example with parentheses:** `=(5+2)*3` results in 21 (5+2 happens first).\n* **Application:** Always use `( )` to group calculations and force the correct order.",
    "3.3.5": "* **The Process:** Once you write a formula in the top cell, click the AutoFill handle (bottom right square) and drag it down the column.\n* **Relative Referencing:** Excel is smart. If your formula is `=A2+B2`, and you copy it down to row 3, Excel automatically changes the formula to `=A3+B3`.\n* **Efficiency:** You only ever need to write a formula once per column.",
    "3.3.6": "* **Step 1:** Create columns for 'Base Fare', 'Baggage Fee', and 'Total Cost'.\n* **Step 2:** In the first 'Total Cost' cell, type `=`. Click the Base Fare cell, type `+`, click the Baggage Fee cell, and press Enter.\n* **Step 3:** Use the AutoFill handle to drag the formula down for all 10 passengers.\n* **Step 4:** Verify that row 5's formula correctly references row 5 data.",
    "3.4.1": "* **Definition:** A cell reference that automatically changes when copied to another cell.\n* **How it works:** Excel doesn't remember 'Cell A2'. It remembers 'One cell to the left'.\n* **Default Behavior:** All cell references (e.g., `A1`) are relative by default. This is why AutoFill works so smoothly for row-by-row calculations.",
    "3.4.2": "* **Definition:** A cell reference that is 'locked' and does NOT change when copied.\n* **The Dollar Sign (`$`):** Used to lock references. `$A$1` means both Column A and Row 1 are locked.\n* **Shortcut:** Press `F4` while typing a cell reference to instantly apply dollar signs.\n* **Use Case:** When multiplying an entire column of ticket prices by a single, static 'Tax Rate' cell located at the top of the sheet.",
    "3.4.3": "* **Definition:** Locking only the Row OR the Column, but not both.\n* **Locking the Column (`$A1`):** As you drag across, the column stays A, but the row number changes as you drag down.\n* **Locking the Row (`A$1`):** As you drag down, the row stays 1, but the column letter changes as you drag across.\n* **Use Case:** Creating a multiplication table or complex two-way matrices.",
    "3.4.4": "* **Name Box:** The box to the left of the Formula bar. \n* **How to name:** Select a cell (e.g., `B1` containing a tax rate) -> click the Name Box -> type `TaxRate` -> press Enter.\n* **Benefit:** You can now write formulas like `=TicketPrice * TaxRate` instead of `=A2 * $B$1`. It makes formulas absolute automatically and easy to read.",
    "3.4.5": "* **`#DIV/0!`:** You are dividing a number by zero or an empty cell.\n* **`#NAME?`:** Excel doesn't recognize text in your formula (usually a typo, like typing `=SUMM(A1:A5)` instead of SUM).\n* **`#REF!`:** The formula refers to a cell that is not valid (usually because you deleted the row or column the formula was relying on).\n* **`######`:** Not an error! The column is just too narrow to display the number. Double-click to AutoFit.",
    "3.4.6": "* **Step 1:** Type 'Tax Rate' in cell E1 and '15%' in cell F1.\n* **Step 2:** In your data table, create a 'Tax Amount' column.\n* **Step 3:** Write the formula `=Cost * $F$1` (Press F4 to lock F1).\n* **Step 4:** Drag the formula down. Check the bottom rows to ensure they are still multiplying by F1.\n* **Step 5:** Change F1 to '18%'. Watch all taxes update instantly.",
    "3.5.1": "* **Formulas vs Functions:** A formula is an equation you write manually (`=A1+A2+A3`). A function is a pre-programmed calculation built into Excel (`=SUM(A1:A3)`).\n* **Syntax Structure:** `=FUNCTION_NAME(argument1, argument2)`.\n* **Arguments:** The data inside the parentheses that the function needs to calculate (usually a range of cells).",
    "3.5.2": "* **`=SUM(range)`:** Adds all numbers in a range of cells.\n  * *Example:* `=SUM(B2:B10)` calculates total revenue.\n* **AutoSum (Shortcut `Alt + =`):** The fastest tool in Excel. Click the empty cell below a column of numbers, press `Alt + =`, and Excel automatically writes the SUM function for you.",
    "3.5.3": "* **`=AVERAGE(range)`:** Calculates the arithmetic mean of a range of cells.\n  * *Example:* `=AVERAGE(C2:C20)` finds the average passenger age or average ticket price.\n* **Important Note:** Empty cells are ignored by the AVERAGE function, but cells containing a '0' are included and will drag the average down.",
    "3.5.4": "* **`=MAX(range)`:** Finds the largest (maximum) number in a range.\n  * *Example:* `=MAX(D2:D50)` finds the highest ticket price paid.\n* **`=MIN(range)`:** Finds the smallest (minimum) number in a range.\n  * *Example:* `=MIN(D2:D50)` finds the lowest ticket price paid.",
    "3.5.5": "* **`=COUNT(range)`:** Counts the number of cells that contain ONLY NUMBERS.\n* **`=COUNTA(range)`:** Counts the number of cells that are NOT EMPTY (includes text, numbers, errors).\n  * *Use Case:* Use COUNTA on a 'Passenger Name' column to see how many people are on the manifest. Using COUNT would return 0 because names are text.",
    "3.5.6": "* **Step 1:** Open the `Daily_Manifest` dataset.\n* **Step 2:** Use `=COUNTA()` to determine the total number of passengers boarded.\n* **Step 3:** Use `=AVERAGE()` on the baggage weight column.\n* **Step 4:** Use `=MAX()` and `=MIN()` to find the heaviest and lightest bags.\n* **Step 5:** Use AutoSum to find the total combined baggage weight.",
    "3.6.1": "* **The IF Function:** Tests a condition and returns one value if True, and another if False.\n* **Syntax:** `=IF(logical_test, value_if_true, value_if_false)`\n* **Example:** `=IF(B2>23, \"Overweight\", \"OK\")`. If the bag in B2 is over 23kg, print 'Overweight'. Otherwise, print 'OK'.\n* **Operators:** `>`, `<`, `=`, `>=`, `<=`, `<>` (not equal to).",
    "3.6.2": "* **Definition:** Placing an IF function *inside* another IF function to test multiple conditions.\n* **Example:** `=IF(B2>32, \"Reject\", IF(B2>23, \"Fee\", \"OK\"))`.\n  * Logic flow: Is it over 32? Yes -> Reject. No -> Is it over 23? Yes -> Fee. No -> OK.\n* **Modern Alternative:** Excel now has the `=IFS()` function which is much easier to read for multiple conditions.",
    "3.6.3": "* **Purpose:** Joins (concatenates) text from multiple cells into one single cell.\n* **Syntax:** `=CONCATENATE(A2, \" \", B2)` or using the ampersand `=A2 & \" \" & B2`.\n* **Use Case:** You have 'First Name' in column A and 'Last Name' in column B. You use this to combine them into a 'Full Name' column. Always remember to add `\" \"` to insert a space!",
    "3.6.4": "* **`=UPPER(text)`:** Converts all text to UPPERCASE (e.g., 'john' -> 'JOHN'). Useful for standardizing airport codes (jfk -> JFK).\n* **`=LOWER(text)`:** Converts all text to lowercase.\n* **`=PROPER(text)`:** Capitalizes the first letter of each word (e.g., 'john doe' -> 'John Doe'). Excellent for cleaning up messy passenger name entries.",
    "3.6.5": "* **Purpose:** Extracts specific characters from a text string.\n* **`=LEFT(text, num)`:** Extracts characters from the far left (e.g., `=LEFT(\"Boeing737\", 6)` returns \"Boeing\").\n* **`=RIGHT(text, num)`:** Extracts characters from the far right.\n* **`=MID(text, start_num, num)`:** Extracts characters from the middle (e.g., extracting the middle numbers from a PNR).",
    "3.6.6": "* **Step 1:** You have a messy list of passenger names in all lowercase. Create a new column and use `=PROPER()` to fix them.\n* **Step 2:** Use `=LEFT()` to extract the 3-letter airport code from a routing string (e.g., \"JFK-LHR\").\n* **Step 3:** Use an `=IF()` statement to flag passengers whose frequent flyer miles are > 50,000 as \"VIP\".",
    "3.7.1": "* **Sorting:** Reordering rows of data based on the contents of one column.\n* **A to Z / Z to A:** Sorts text alphabetically, dates chronologically, and numbers lowest-to-highest.\n* **How to Sort:** Click *any single cell* in the column you want to sort by, go to Data Tab -> Click A-Z.\n* **Warning:** Never highlight a single column and sort! It will scramble the data. Just click one cell, and Excel will sort the whole row.",
    "3.7.2": "* **Purpose:** Sorting by multiple columns sequentially.\n* **Example:** Sort by 'Destination' (A-Z), and *then* by 'Departure Time' (Newest to Oldest).\n* **How to do it:** Data Tab -> Sort (the big square button). Add a level for the primary sort, click 'Add Level', and set the secondary sort.",
    "3.7.3": "* **Filters:** Hide rows of data that do not meet your criteria. The data isn't deleted, just temporarily hidden.\n* **How to apply:** Click anywhere in your data -> Data Tab -> Filter (funnel icon). Drop-down arrows appear on headers.\n* **Basic usage:** Click a drop-down, uncheck 'Select All', and check only 'Delayed' to view only delayed flights.",
    "3.7.4": "* **Number Filters:** Allows logical filtering (e.g., Greater Than, Less Than, Between). \n  * *Example:* Filter 'Ticket Price' -> Greater Than -> 500.\n* **Text Filters:** Allows pattern matching.\n  * *Example:* Filter 'Destination' -> Contains -> 'York' (will find New York, Yorkshire).\n* **Clearing Filters:** Data Tab -> Clear to view all data again.",
    "3.7.5": "* **Find (`Ctrl + F`):** Searches the entire worksheet for a specific word, number, or phrase.\n* **Replace (`Ctrl + H`):** Finds a value and replaces it with another.\n  * *Use Case:* An airline changes its code from 'AI' to 'AIA'. You can instantly find all 'AI' entries and replace them with 'AIA' across 10,000 rows.",
    "3.7.6": "* **Step 1:** Turn on Filters for the manifest table.\n* **Step 2:** Filter the 'Status' column to show only 'Checked-In' passengers.\n* **Step 3:** Apply a Number Filter to show passengers with baggage > 20kg.\n* **Step 4:** Clear all filters.\n* **Step 5:** Perform a Multi-level Sort: By Class (First, Business, Econ) then by Name (A-Z).",
    "3.8.1": "* **Why visualize?** Humans process visual patterns much faster than raw grids of numbers.\n* **Data Storytelling:** Charts highlight trends, outliers, and comparisons to help management make quick decisions.\n* **Rule of Thumb:** Keep charts clean. Remove unnecessary gridlines, excessive colors, and distracting 3D effects.",
    "3.8.2": "* **Column Charts (Vertical):** Best for comparing different categories side-by-side (e.g., Revenue by Quarter).\n* **Bar Charts (Horizontal):** Best when category names are very long and wouldn't fit well horizontally.\n* **How to create:** Highlight your data (including labels) -> Insert Tab -> Recommended Charts -> Select Column/Bar.",
    "3.8.3": "* **Pie Charts:** Best for showing parts of a whole (percentages that add up to 100%).\n  * *Limitation:* Never use a pie chart if you have more than 5 categories (it becomes unreadable).\n* **Line Charts:** Best for showing trends over time (e.g., Daily passenger volume over a month).\n  * *Rule:* Time should always be on the horizontal X-axis.",
    "3.8.4": "* **Chart Title:** Must be descriptive (e.g., \"Q3 Passenger Growth\" not just \"Chart\").\n* **Data Labels:** Numbers appearing directly on the bars or pie slices so users don't have to guess the exact value.\n* **Legends:** The key telling you what colors mean. Move it to the top or bottom for better layout.\n* **Access:** Click the Chart -> Click the green '+' icon on the top right corner of the chart.",
    "3.8.5": "* **Changing Type:** Chart Design Tab -> Change Chart Type. Instantly swap a Column chart for a Line chart to see which looks better.\n* **Select Data:** Right-click chart -> Select Data. Use this to add new data series (lines) to an existing chart, or fix labels if Excel guessed incorrectly.\n* **Switch Row/Column:** Swaps the X-axis data with the Legend data.",
    "3.8.6": "* **Step 1:** Select a small table of 'Monthly Revenue' data.\n* **Step 2:** Insert a 2D Line Chart to show the trend over the year.\n* **Step 3:** Add Data Labels and remove gridlines for a cleaner look.\n* **Step 4:** Change the Chart Title to '2026 Monthly Revenue Trend'.\n* **Step 5:** Move the chart to a dedicated 'Dashboard' worksheet.",
    "3.9.1": "* **Definition:** Changes the color/formatting of a cell automatically based on its value.\n* **Highlight Cell Rules:** Home Tab -> Conditional Formatting.\n  * *Greater/Less Than:* E.g., Highlight all delays > 30 mins in Red.\n  * *Text that Contains:* E.g., Highlight the word 'Cancelled' with a red background.",
    "3.9.2": "* **Data Bars:** Fills the cell with a colored bar proportional to the cell's value. Creates a mini-bar chart directly inside the cell!\n* **Color Scales:** Applies a heat-map gradient to a range of numbers (e.g., Green for high revenue, Red for low revenue).\n* **Icon Sets:** Adds mini icons (like traffic lights or arrows) based on thresholds.",
    "3.9.3": "* **The Problem:** Data entry errors often result in the same passenger or invoice being entered twice.\n* **The Solution:** Highlight the dataset -> Data Tab -> Remove Duplicates.\n* **How it works:** You check the boxes for columns that must be identical to count as a duplicate. Excel deletes the copies and keeps the first unique instance.",
    "3.9.4": "* **Purpose:** Splits data from one column into multiple columns based on a delimiter (like a comma or space).\n* **Use Case:** You export data and get 'Lastname, Firstname' in one cell. You want them in two separate cells.\n* **Steps:** Highlight the column -> Data Tab -> Text to Columns -> Delimited -> Choose 'Comma' -> Finish.",
    "3.9.5": "* **Purpose:** Restricts what users can type into a cell to prevent errors.\n* **Drop-Down Lists:** Data Tab -> Data Validation -> Allow: List.\n  * *Source:* Type items separated by commas (e.g., `Economy, Business, First`) or select a range of cells.\n* **Benefit:** Ensures perfect data consistency (no more fixing 'Econ', 'Eco', 'Economy' typos).",
    "3.9.6": "* **Step 1:** Select the 'Crew Class' column and apply Data Validation to create a drop-down list (Pilot, Copilot, Cabin Crew).\n* **Step 2:** Select the dataset and click 'Remove Duplicates' to clean up accidental double-entries.\n* **Step 3:** Use Text-to-Columns to split a 'Full Name' column into 'First Name' and 'Last Name'.\n* **Step 4:** Apply Conditional Formatting to highlight all 'Expired' certifications in Red.",
    "3.10.1": "* **Page Layout View:** View Tab -> Page Layout. Shows exactly where the page breaks will cut your data.\n* **Orientation:** Switch to Landscape (Page Layout Tab) for wide spreadsheets with many columns.\n* **Scaling (Fit to Page):** Page Layout Tab -> Scale to Fit. \n  * *Pro Tip:* Set Width to '1 page' to force all columns onto one page, letting the rows flow naturally to page 2.",
    "3.10.2": "* **Print Area:** Highlights only a specific part of a massive spreadsheet to print. (Select cells -> Page Layout -> Print Area -> Set Print Area).\n* **Page Breaks:** Insert manual breaks to force specific sections onto a new page (Page Layout -> Breaks -> Insert Page Break).",
    "3.10.3": "* **The Problem:** When printing a 5-page list, pages 2-5 will just have raw numbers with no header row to explain what the columns mean.\n* **The Solution:** Page Layout Tab -> Print Titles.\n* **Steps:** Click 'Rows to repeat at top' -> Click Row 1 -> OK. Now Row 1 prints at the top of every physical page.",
    "3.10.4": "* **Access:** View Tab -> Page Layout view. Click in the header/footer zones.\n* **Dynamic Elements:** Header & Footer tools allow you to insert dynamic codes like `&[Page]` (current page number), `&[Date]` (today's date), and `&[File]` (the filename).\n* **Best Practice:** Always put page numbers in the footer of multi-page spreadsheets.",
    "3.10.5": "* **Review Topics:** \n  * Data entry, formatting, and cell referencing (Absolute vs Relative).\n  * Core functions (SUM, AVERAGE, IF) and Text operations.\n  * Data analysis (Sorting, Filters, Conditional Formatting, Drop-downs).\n  * Visuals and Output (Charts, Print scaling, Print Titles).\n* **Q&A:** Open floor for student questions.",
    "3.10.6": "* **Task Overview:** You will be given a raw CSV file of unformatted monthly sales data.\n* **Requirements:**\n  1. Format headers and apply Number formats.\n  2. Use formulas and absolute referencing to calculate taxes and totals.\n  3. Use IF functions to categorize performance.\n  4. Create a Bar chart summarizing total sales per region.\n  5. Set up the page to print on a single Landscape page with repeating print titles.",

    # UNIT 4
    "4.1.1": "* **Thumbnails Pane:** The left sidebar showing miniature versions of all slides.\n* **Slide Pane:** The large central area where you edit the active slide.\n* **Notes Pane:** Hidden at the bottom; used for speaker notes that the audience won't see.\n* **Views:** Normal View (editing), Slide Sorter (rearranging), Reading/Slide Show View (presenting).",
    "4.1.2": "* **Creation:** File -> New -> Blank Presentation (Shortcut: `Ctrl + N`).\n* **Title Slide:** The default first slide. Enter the presentation title and speaker name.\n* **Saving:** File -> Save As (`F12`). Save early and often. `Ctrl + S` updates the save.",
    "4.1.3": "* **New Slide (`Ctrl + M`):** Home Tab -> New Slide. (Note: `Ctrl + N` makes a new file, `Ctrl + M` makes a new slide).\n* **Duplicating (`Ctrl + D`):** Instantly creates an exact copy of the selected slide. Great for keeping complex layouts consistent.\n* **Deleting:** Click the slide thumbnail and press `Delete` or `Backspace`.",
    "4.1.4": "* **Definition:** Pre-arranged layouts of placeholders (Title and Content, Two Content, Picture with Caption).\n* **Changing Layouts:** Home Tab -> Layout. \n* **Why use them?** Layouts keep formatting consistent and ensure that when you apply a design theme, the text moves to the correct spot automatically. Do not just insert random text boxes!",
    "4.1.5": "* **Placeholders:** The dotted boxes that say 'Click to add text'.\n* **Bullet Points:** The default text format in PowerPoint. \n  * *Tip:* Press `Tab` to indent a bullet point (sub-point), and `Shift + Tab` to outdent it.\n* **Formatting Text:** Identical to MS Word (Font, Size, Bold, Color). Maintain high contrast (dark text on light backgrounds or vice versa).",
    "4.1.6": "* **Step 1:** Create a new presentation with 5 slides.\n* **Step 2:** Slide 1 (Title Layout): Company Name and Slogan.\n* **Step 3:** Slide 2 (Title & Content): 'About Us' with 3 bullet points.\n* **Step 4:** Slide 3 (Two Content): 'Our Fleet' - text on the left, placeholder empty on the right.\n* **Step 5:** Duplicate Slide 3 to create Slide 4 for 'Our Destinations'.",
    "4.2.1": "* **Design Tab:** Contains professionally crafted Themes (color palettes, fonts, and background graphics).\n* **Applying a Theme:** Click a theme to apply it to all slides. \n* **Variants:** Next to the themes, you can click 'Variants' to keep the design but change the color scheme (e.g., from Blue to Green).",
    "4.2.2": "* **Customizing Colors:** Design Tab -> Variants -> Colors. You can set specific RGB codes to match your airline/corporate branding.\n* **Customizing Fonts:** Design Tab -> Variants -> Fonts. Sets the master Heading and Body fonts for the entire presentation.\n* **Consistency:** Always use these global settings rather than changing font colors manually on every single slide.",
    "4.2.3": "* **Background Styles:** Design Tab -> Format Background.\n* **Solid/Gradient Fill:** Change the slide canvas to a specific color or gradient.\n* **Picture Fill:** Use a company photo as the background. \n  * *Crucial Step:* Increase the 'Transparency' slider so the background image doesn't make the text unreadable!",
    "4.2.4": "* **What is the Slide Master?** The behind-the-scenes architectural blueprint of your slides (View Tab -> Slide Master).\n* **Why use it?** If you want to add a company logo to the bottom right of *every* slide, do not paste it 50 times. Paste it *once* on the Master Slide, and it appears everywhere.\n* **Exiting:** You must click 'Close Master View' to return to normal editing.",
    "4.2.5": "* **Creating a Template (`.potx`):** Once you have set up your master slides, colors, and logos, go to File -> Save As.\n* **Change File Type:** Select 'PowerPoint Template (*.potx)'.\n* **Benefit:** Future presentations can be started from this template, ensuring every employee creates slides that are 100% on-brand.",
    "4.2.6": "* **Step 1:** Open the 5-slide company intro.\n* **Step 2:** Go to View -> Slide Master.\n* **Step 3:** Insert a small 'Company Logo' shape in the top right corner of the primary master slide.\n* **Step 4:** Change the Master Title font to a bold, modern typeface.\n* **Step 5:** Close Master View and verify the changes applied to all 5 slides instantly.",
    "4.3.1": "* **Inserting:** Insert Tab -> Pictures / Icons.\n* **Resizing:** Always drag from the *corner* handles to keep the image proportional. Dragging the sides will stretch and distort the image.\n* **Alignment:** Use the red 'Smart Guides' that appear as you drag an image to align it perfectly centered or flush with text.",
    "4.3.2": "* **Inserting Shapes:** Insert -> Shapes. Hold the `Shift` key while drawing a circle or square to make it a perfect circle/square.\n* **Text in Shapes:** Simply click a shape and start typing; the text is automatically centered inside.\n* **Formatting:** Shape Format Tab. Adjust Shape Fill, Shape Outline, and Shape Effects (shadows, reflections).",
    "4.3.3": "* **What is SmartArt?** A tool that instantly converts boring bullet points into professional graphics.\n* **How to use:** Highlight your bullet points -> Right-click -> 'Convert to SmartArt'.\n* **Types:** \n  * *List/Process:* Good for timelines or steps.\n  * *Hierarchy:* Good for organizational charts.\n  * *Cycle:* Good for continuous loops (e.g., feedback loops).",
    "4.3.4": "* **Inserting Tables:** Insert -> Table. Works identically to MS Word.\n* **Inserting Charts:** Insert -> Chart. This opens a mini-Excel window where you paste your data. The chart then renders in PowerPoint.\n* **Best Practice:** Simplify data on slides. Do not paste a massive 50-row Excel spreadsheet. Extract the key numbers and make a clean, simple chart.",
    "4.3.5": "* **Inserting Video:** Insert -> Video. You can upload from your PC or link from YouTube.\n* **Playback Options:** Video Format/Playback Tab. Set it to start 'Automatically' or 'When Clicked'. \n* **Trimming:** You can trim the start/end of an embedded video directly inside PowerPoint without external video editors.",
    "4.3.6": "* **Step 1:** Create a new slide titled 'Evacuation Procedure'.\n* **Step 2:** Type 3 steps: Brace, Unbuckle, Evacuate.\n* **Step 3:** Convert the text into a 'Process' SmartArt graphic.\n* **Step 4:** Insert an icon of an airplane next to the title.\n* **Step 5:** Insert an emergency exit graphic and apply a 'Drop Shadow' shape effect.",
    "4.4.1": "* **Definition:** A Transition is the visual effect that occurs when moving from one slide to the next.\n* **Applying:** Transitions Tab -> Select an effect (Fade, Push, Morph).\n* **Best Practice:** Stick to simple transitions like 'Fade'. Wild effects (Origami, Shatter) distract from a professional presentation.",
    "4.4.2": "* **Duration:** Controls how fast the transition happens (e.g., 1.5 seconds).\n* **Advance Slide:** \n  * *On Mouse Click:* The presenter controls the pace manually.\n  * *After X Seconds:* The slide automatically moves forward (used for automated kiosk displays at airports).",
    "4.4.3": "* **Definition:** Animations control how individual items (text, images) enter, act, or exit *within* a single slide.\n* **Entrance (Green):** How the object appears (e.g., Fade in, Fly in).\n* **Emphasis (Yellow):** Draws attention to an object already on screen (e.g., Pulse, Grow).\n* **Exit (Red):** How the object leaves the screen.",
    "4.4.4": "* **Animation Pane:** Animations Tab -> Animation Pane. The command center for sequencing.\n* **Start Options:**\n  * *On Click:* Wait for presenter to click.\n  * *With Previous:* Animations happen at the exact same time.\n  * *After Previous:* Animation starts automatically after the last one finishes, creating a chain reaction.",
    "4.4.5": "* **The 6x6 Rule:** No more than 6 bullet points per slide, no more than 6 words per line.\n* **Death by PowerPoint:** Avoid reading slides verbatim. The slide is a visual aid, you are the presentation.\n* **Animation Restraint:** Only animate objects if it adds explanatory value (e.g., a flowchart building step-by-step). Never animate just for decoration.",
    "4.4.6": "* **Step 1:** Go to the 'Evacuation Procedure' SmartArt slide.\n* **Step 2:** Select the SmartArt, go to Animations -> 'Fade' entrance effect.\n* **Step 3:** Open Animation Pane, click Effect Options, and choose 'One by One'.\n* **Step 4:** Set the animation to advance 'On Click'.\n* **Step 5:** Go into Slide Show mode to test that the steps appear sequentially upon clicking.",
    "4.5.1": "* **Speaker Notes:** The section beneath the slide in Normal View. \n* **Purpose:** Write your script or key reminders here. The audience will never see these on the projector.\n* **Printing Notes:** File -> Print -> Print Layout: 'Notes Pages'. Prints a thumbnail of the slide with your notes underneath.",
    "4.5.2": "* **Slide Show Tab:** Click 'From Beginning' (`F5`) or 'From Current Slide' (`Shift + F5`).\n* **Presenter View:** The ultimate tool for speakers. \n  * *Audience sees:* Only the full-screen slide on the projector.\n  * *You see on your laptop:* The current slide, your secret speaker notes, a timer, and a preview of the *next* slide so you can seamlessly transition.",
    "4.5.3": "* **Handouts:** File -> Print -> Print Layout: 'Handouts'.\n* **Options:** You can print 3, 4, or 6 slides per page to save paper. \n* **'3 Slides' Option:** The most popular handout format, as it prints thumbnails on the left and blank lines on the right for audience note-taking.",
    "4.5.4": "* **Exporting to PDF:** File -> Save As -> `.pdf`. Great for emailing slides to clients securely without them messing up the fonts/formatting.\n* **Exporting to Video:** File -> Export -> Create a Video. Turns your timed animations and recorded voiceovers into an MP4 file.",
    "4.5.5": "* **Review Topics:** \n  * Slide creation, Layouts, and Placeholders.\n  * Slide Master, Themes, and consistent Branding.\n  * Integrating Images, SmartArt, and Video.\n  * Professional rules for Animations and Transitions.\n  * Presenter View and Exporting options.\n* **Q&A:** Open floor for student questions.",
    "4.5.6": "* **Task:** You will receive raw text and 3 images regarding an 'Aviation Safety Update'.\n* **Requirements:**\n  1. Create a 5-slide deck using a custom Slide Master logo.\n  2. Convert a list of safety steps into an animated SmartArt graphic (One-by-one).\n  3. Add Speaker Notes to at least two slides.\n  4. Hook up to the projector, launch Presenter View, and deliver a 2-minute mock presentation.",

    # UNIT 5
    "5.1.1": "* **The Internet:** The global network of connected computers and servers.\n* **The WWW (World Wide Web):** The collection of webpages and documents accessed *via* the Internet.\n* **HTTP/HTTPS:** The protocol used to transfer web pages. The 'S' stands for Secure (encrypted data).",
    "5.1.2": "* **Web Browsers:** Software applications used to access and view websites (Google Chrome, MS Edge, Mozilla Firefox, Safari).\n* **Tabs vs Windows:** Use tabs (`Ctrl + T`) to open multiple pages within one browser window for better resource management.\n* **Incognito/Private Browsing:** Opens a window that does not save history, cookies, or form data. Useful for using public computers.",
    "5.1.3": "* **URL (Uniform Resource Locator):** The web address (e.g., `https://www.google.com/images`).\n* **Domain Names:** The readable name of the website (e.g., `google.com`).\n* **Top-Level Domains (TLDs):** Indicates the site's purpose or origin (`.com` for commercial, `.edu` for education, `.gov` for government, `.aero` for aviation).",
    "5.1.4": "* **Keywords:** Use concise noun phrases rather than full sentences.\n* **Search Operators:**\n  * *Quotes (`\"\"`):* Forces exact match (e.g., `\"Boeing 737 Max\"`).\n  * *Minus (`-`):* Excludes a word (e.g., `Aviation jobs -pilot`).\n  * *Site limit (`site:`):* Searches within one specific website (e.g., `site:faa.gov safety regulations`).",
    "5.1.5": "* **Bookmarks/Favorites (`Ctrl + D`):** Saves a website URL for quick access later.\n* **Bookmark Manager:** Organize saved sites into folders (e.g., 'Aviation News', 'Flight Trackers').\n* **Browsing History (`Ctrl + H`):** View previously visited pages. Regularly clear your cache and cookies if websites are behaving incorrectly.",
    "5.1.6": "* **Step 1:** Open Chrome and create a new Bookmark Folder named 'Aviation Research'.\n* **Step 2:** Use the `site:` operator to search for recent press releases on `boeing.com`.\n* **Step 3:** Find a relevant article and bookmark it into your new folder.\n* **Step 4:** Open an Incognito window and verify that your browsing history is empty.",
    "5.2.1": "* **Email Clients:** Desktop applications like Microsoft Outlook or Apple Mail.\n* **Webmail:** Accessing email via a browser (Gmail, Outlook.com).\n* **Professionalism:** An email address should be professional (e.g., `firstname.lastname@airline.com`), not casual (`flyboy99@yahoo.com`).",
    "5.2.2": "* **Subject Line:** Must be clear, specific, and actionable (e.g., 'Action Required: Updated Roster for March').\n* **Salutation & Sign-off:** Always use professional greetings ('Dear...', 'Hello...') and closings ('Best regards,', 'Sincerely,').\n* **Reply vs Reply All:** ONLY use Reply All if every single person on the chain needs to know your specific response.",
    "5.2.3": "* **To:** The primary recipient(s) who are expected to take action.\n* **CC (Carbon Copy):** Kept in the loop for informational purposes, but no action is expected of them.\n* **BCC (Blind Carbon Copy):** Recipients are hidden from everyone else. \n  * *Use Case:* Mass emailing 50 clients to protect their privacy, or secretly keeping a manager informed.",
    "5.2.4": "* **Attachments:** Clicking the paperclip icon to send files (PDFs, Spreadsheets).\n* **Size Limits:** Most email servers reject emails larger than 20MB - 25MB.\n* **The Solution:** For large files (like high-res videos or databases), upload the file to Cloud Storage (Drive/OneDrive) and email a *link* to the file instead.",
    "5.2.5": "* **Folders/Labels:** Creating specific buckets for emails (e.g., 'HR Updates', 'Client A', 'Travel Receipts').\n* **Filters/Rules:** Automating your inbox. \n  * *Example:* Set a rule: \"If email is from the CEO, flag as High Importance and move to 'Urgent' folder.\"\n* **Archiving vs Deleting:** Archiving removes it from the inbox but keeps it searchable forever. Deleting moves it to Trash to be permanently erased.",
    "5.2.6": "* **Step 1:** Compose an email to your instructor.\n* **Step 2:** Add a descriptive Subject Line regarding a 'Mock Schedule'.\n* **Step 3:** Use a professional greeting and sign-off.\n* **Step 4:** CC a classmate, and BCC yourself.\n* **Step 5:** Attach the `Passenger_List.xlsx` file created in Unit 3, and hit Send.",
    "5.3.1": "* **Definition:** Storing and accessing data and programs over the Internet instead of your computer's local hard drive.\n* **Benefits:**\n  * *Accessibility:* Access files from any device, anywhere in the world.\n  * *Security:* Immune to your laptop crashing or being stolen.\n  * *Collaboration:* Multiple people can edit the same file simultaneously.",
    "5.3.2": "* **Google Drive / MS OneDrive:** The industry standards for cloud storage.\n* **The Interface:** Similar to Windows File Explorer. You can create folders, upload files, and move things around.\n* **Desktop Sync:** Apps that map your cloud storage to look like a normal folder (e.g., `C:\\Users\\Admin\\OneDrive`). Files saved here instantly upload to the cloud.",
    "5.3.3": "* **Uploading:** Drag and drop files from your desktop directly into the browser window.\n* **Organizing:** Create folders (e.g., '2026 Flight Logs') and keep them structured.\n* **Offline Access:** You can flag certain critical cloud files to be kept 'Available Offline' so you can work on them during a flight without Wi-Fi.",
    "5.3.4": "* **Sharing Links:** Instead of emailing attachments, generate a shareable link.\n* **Permission Levels:**\n  * *Viewer:* Can read and download, but cannot make changes.\n  * *Commenter:* Can leave sticky-note suggestions without altering the original text.\n  * *Editor:* Has full control to delete, type, and modify the document.",
    "5.3.5": "* **Simultaneous Editing:** In Google Docs or Word Online, you can see your colleagues' cursors typing in real-time.\n* **Version History:** The cloud tracks every keystroke. If someone accidentally deletes a paragraph, you can go to File -> Version History and restore the document to how it looked yesterday.",
    "5.3.6": "* **Step 1:** Open Google Docs / Word Online and create a new document titled 'Group Project'.\n* **Step 2:** Share the document with the person sitting next to you, giving them 'Editor' access.\n* **Step 3:** Both students log in and simultaneously type your names and favorite airlines.\n* **Step 4:** Try using the 'Suggesting/Reviewing' mode to leave a comment on their text.",
    "5.4.1": "* **The Threat Landscape:** Airlines handle massive amounts of sensitive data (passports, credit cards, flight paths).\n* **The Human Element:** 90% of successful cyber attacks occur because an employee made a mistake, not because of hacking software.\n* **Consequences:** Data breaches lead to severe financial penalties (GDPR), loss of reputation, and operational shutdowns.",
    "5.4.2": "* **Phishing:** Fraudulent emails designed to trick you into revealing passwords or clicking malicious links.\n* **Red Flags:**\n  1. Urgent, threatening language (\"Your account will be suspended in 24 hours!\").\n  2. Generic greetings (\"Dear Customer\").\n  3. Mismatched URLs (Hovering over a link shows it goes to `apple-support-login.com` instead of `apple.com`).\n  4. Unexpected attachments.",
    "5.4.3": "* **Length beats complexity:** `CorrectHorseBatteryStaple` is much harder for a computer to crack than `P@$$w0rd`.\n* **Password Reuse:** NEVER use the same password for your airline login that you use for your personal Netflix account. If Netflix gets hacked, hackers will try that password everywhere.\n* **Two-Factor Authentication (2FA):** Always enable 2FA. Even if a hacker steals your password, they cannot log in without the code sent to your phone.",
    "5.4.4": "* **Malware:** Broad term for 'Malicious Software' (Viruses, Worms, Trojans).\n* **Ransomware:** A specific, highly dangerous malware that encrypts all files on a computer and demands payment to unlock them.\n* **Antivirus:** Always keep Windows Defender enabled and updated. Do not plug in random USB drives found in airports or parking lots (USB Drop attacks).",
    "5.4.5": "* **HTTPS:** Look for the padlock icon in the browser address bar. Never enter passwords or credit cards on sites that say 'Not Secure'.\n* **Downloading:** Only download software from official vendor websites. Never use third-party cracked software sites.\n* **Public Wi-Fi:** Airport and coffee shop Wi-Fi networks are public. Do not check sensitive bank accounts without using a VPN (Virtual Private Network).",
    "5.4.6": "* **Step 1:** Go to a safe website like `haveibeenpwned.com` to check if your personal email has been involved in a data breach.\n* **Step 2:** Open Windows Security / Windows Defender settings and run a 'Quick Scan'.\n* **Step 3:** Review your browser's saved passwords list and delete any weak/old ones.\n* **Step 4:** Analyze 3 example 'Phishing' emails provided by the instructor and identify the red flags.",
    "5.5.1": "* **The Shift:** Remote work and global aviation teams rely heavily on Video Conferencing.\n* **Zoom / MS Teams:** Industry leaders for video calls, webinars, and enterprise communication.\n* **Key Features:** Waiting rooms, host controls (muting participants), chat boxes, and recording capabilities.",
    "5.5.2": "* **Scheduling:** Generating a calendar invite with a unique meeting link, meeting ID, and passcode.\n* **Hardware Check:** Always test your microphone and webcam in the settings *before* joining the call.\n* **Backgrounds:** Use a clean, distraction-free physical background, or utilize 'Virtual Backgrounds'/'Background Blur' for professionalism.",
    "5.5.3": "* **Screen Sharing:** Sharing your entire desktop vs sharing a specific application window (Application sharing is safer to prevent accidental pop-ups).\n* **Mute Discipline:** Keep your microphone muted when you are not speaking to eliminate background noise.\n* **Eye Contact:** Look at the *camera* lens when speaking, not at the screen, to simulate real eye contact.",
    "5.5.4": "* **Slack / Teams Chat:** Replacing internal email with real-time text channels.\n* **Channels vs DMs:** Use specific channels for team topics (e.g., `#flight-ops`), and Direct Messages for 1-on-1 chats.\n* **Etiquette:** \n  * Use threads to keep conversations organized.\n  * Set your status (e.g., 'In a Meeting', 'Out of Office').\n  * Keep messages concise and professional.",
    "5.5.5": "* **Review Topics:** \n  * Browsers, Search Operators, and Bookmarks.\n  * Professional Email (CC/BCC, rules, attachments).\n  * Cloud Storage and Live Collaboration.\n  * Cyber Safety (Phishing, Passwords, Public Wi-Fi).\n  * Digital Comms (Zoom etiquette, Slack).\n* **Q&A:** Open floor for student questions.",
    "5.5.6": "* **Task Overview:** A capstone communication exercise.\n* **Requirements:**\n  1. Create a meeting invite for a mock scenario and email it to a partner using CC.\n  2. Upload a document to Cloud Storage and reply to the email with a sharing link.\n  3. Initiate a video call, share your screen, and explain 3 phishing red flags using a visual aid."
}

# The files have headers like: # 1.1.2 Identifying central processing units (CPU) and memory
for dirpath in [r"curriculum-app/src/content/computing-skills/ug/bba-aviation/sem1", r"curriculum-app/src/content/computing-skills/ug/bsc-aviation/sem1"]:
    if not os.path.exists(dirpath):
        continue
    for filename in os.listdir(dirpath):
        if not filename.endswith('.md'):
            continue
        
        filepath = os.path.join(dirpath, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # We want to find sections like:
        # # 1.1.2 Some Title\n\nInstructor will guide you through this concept.\n\n---
        # OR
        # # 1.1.6 Hands-on: Examining hardware components\n\nFollow the instructor's demonstration in the lab to complete this exercise.\n\n---
        
        for key, replacement_text in content_map.items():
            # Create a regex to find the section for this key
            pattern = r'(# ' + key + r' [^\n]+)\n\n(?:Instructor will guide you through this concept\.|Follow the instructor\'s demonstration in the lab to complete this exercise\.)\n\n---'
            def replacer(match, text=replacement_text):
                return match.group(1) + '\n\n' + text + '\n\n---'
            content = re.sub(pattern, replacer, content)
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

print("Expanded content successfully applied to all slides.")
